In [4]:
import numpy
n = numpy.arange(27)
n.reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
import cv2
im_g = cv2.imread('smallgray.png',0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
cv2.imwrite('smallgray1.png',im_g)

True

In [16]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [21]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [7]:
#im_s = numpy.hstack((im_g, im_g))
#im_s
im_s = numpy.vstack((im_g, im_g))
im_s

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
#lst = numpy.hsplit(im_s,5)
lst = numpy.vsplit(im_s,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]